# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Wheel

on:
  workflow_dispatch:

jobs:


  build:
    strategy:
      max-parallel: 2
      # let some wheels complete even if others fail
      fail-fast: false
      matrix:
        python_version: ['3.8', '3.9']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        architecture: x64

    - name: Setup Java JDK
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 8
        distribution: adopt
    - name: Build with Maven
      run: |
        mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e --settings .mvn/custom-settings.xml
        mvn test -B --settings .mvn/custom-settings.xml

    - name: Build Python package
      run: python setup.py bdist_wheel

    - id: get_version
      uses: battila7/get-version-action@v2

    - id: inspection
      run: |
          echo ${{ steps.get_version.outputs.version-without-v }}
          ls -al .


    #- name: Store artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: prokaryote-${{ steps.get_version.outputs.version-without-v }}.tar.gz
    #    name: cibw-wheels-cp${{ matrix.python }}-${{ matrix.platform_id }}
    #    path: ./wheelhouse/*.whl
